# Generated by Django 5.0 on 2024-07-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_blogtable_author_blogtable_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='stepno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
